### ISSUE TITLE
Give the current UTDMakerspace Officers Access to this organization

### ISSUE THREAD

**Issue by ATechAdventurer** [utdmakerspace/utdmakerspace.github.io#17]
@rahulsonwalkar
@vivngo
@qriusGate
@AbhinavChennapareddy

**Comment by rahulsonwalkar** [comment]
@ATechAdventurer  Feel free to make pull requests and we can approve them, or if you can get the Makerspace faculty advisor to send us an email, we'd be happy to transfer over access.

**Comment by ATechAdventurer** [comment]
@rahulsonwalkar what email address should he send an email to?

**Comment by ATechAdventurer** [comment]
@rahulsonwalkar I had our Faculty Advisor, Rod Wetterskog send an email to the address listed on your profile.
